2025-08-22 10:54:37,714: INFO: main: Alhumdullillah sb okay h boss!
[2025-08-22 11:12:50,758: INFO: main: Alhumdullillah sb okay h boss!]
[2025-08-22 18:53:12,075: ERROR: main: name 'STAGE_NAME' is not defined]
Traceback (most recent call last):
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\main.py", line 5, in <module>
    logger.info(f'>>>>> stage {STAGE_NAME} started >>>>>')
                               ^^^^^^^^^^
NameError: name 'STAGE_NAME' is not defined
[2025-08-22 18:53:42,782: INFO: main: >>>>> stage Data Ingestion Stage started >>>>>]
[2025-08-22 18:53:42,783: ERROR: main: Argument path_to_yaml of type <class 'pathlib.WindowsPath'> to <function read_yaml at 0x000002A1D73D00E0> does not match annotation type <class 'str'>]
Traceback (most recent call last):
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\main.py", line 11, in <module>
    obj.initiate_data_ingestion()
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\pipeline\DataIngestionPipeline.py", line 13, in initiate_data_ingestion
    config = ConfigurationManager()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\config\configuration.py", line 12, in __init__
    self.config = read_yaml(config_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\.venv\Lib\site-packages\ensure\main.py", line 870, in __call__
    raise EnsureError(msg.format(arg=arg, f=self.f, t=templ, valt=type(value)))
ensure.main.EnsureError: Argument path_to_yaml of type <class 'pathlib.WindowsPath'> to <function read_yaml at 0x000002A1D73D00E0> does not match annotation type <class 'str'>
[2025-08-22 18:54:16,466: INFO: main: >>>>> stage Data Ingestion Stage started >>>>>]
[2025-08-22 18:54:16,467: ERROR: main: Argument path_to_yaml of type <class 'pathlib.WindowsPath'> to <function read_yaml at 0x00000262903A00E0> does not match annotation type <class 'str'>]
Traceback (most recent call last):
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\main.py", line 11, in <module>
    obj.initiate_data_ingestion()
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\pipeline\DataIngestionPipeline.py", line 13, in initiate_data_ingestion
    config = ConfigurationManager()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\config\configuration.py", line 12, in __init__
    self.config = read_yaml(config_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\.venv\Lib\site-packages\ensure\main.py", line 870, in __call__
    raise EnsureError(msg.format(arg=arg, f=self.f, t=templ, valt=type(value)))
ensure.main.EnsureError: Argument path_to_yaml of type <class 'pathlib.WindowsPath'> to <function read_yaml at 0x00000262903A00E0> does not match annotation type <class 'str'>
[2025-08-22 18:55:32,743: INFO: main: >>>>> stage Data Ingestion Stage started >>>>>]
[2025-08-22 18:55:32,747: INFO: common: Yaml file: config\config.yaml is loaded successfully]
[2025-08-22 18:55:32,749: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-22 18:55:32,750: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-22 18:55:32,751: ERROR: main: create_directories() missing 1 required positional argument: 'verbose']
Traceback (most recent call last):
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\main.py", line 11, in <module>
    obj.initiate_data_ingestion()
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\pipeline\DataIngestionPipeline.py", line 13, in initiate_data_ingestion
    config = ConfigurationManager()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\config\configuration.py", line 16, in __init__
    create_directories([self.config.artifacts_root])
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\.venv\Lib\site-packages\ensure\main.py", line 835, in __call__
    return self.f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: create_directories() missing 1 required positional argument: 'verbose'
[2025-08-22 18:56:17,830: INFO: main: >>>>> stage Data Ingestion Stage started >>>>>]
[2025-08-22 18:56:17,838: INFO: common: Yaml file: config\config.yaml is loaded successfully]
[2025-08-22 18:56:17,896: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-22 18:56:17,971: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-22 18:56:18,049: ERROR: common: makedirs() got an unexpected keyword argument 'exists_ok']
Traceback (most recent call last):
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\utils\common.py", line 30, in create_directories
    os.makedirs(path_to_directory,exists_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exists_ok'
[2025-08-22 18:56:18,084: ERROR: main: makedirs() got an unexpected keyword argument 'exists_ok']
Traceback (most recent call last):
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\main.py", line 11, in <module>
    obj.initiate_data_ingestion()
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\pipeline\DataIngestionPipeline.py", line 13, in initiate_data_ingestion
    config = ConfigurationManager()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\config\configuration.py", line 17, in __init__
    create_directories([self.config.artifacts_root],verbose=True)
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\.venv\Lib\site-packages\ensure\main.py", line 835, in __call__
    return self.f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\utils\common.py", line 35, in create_directories
    raise e
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\utils\common.py", line 30, in create_directories
    os.makedirs(path_to_directory,exists_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exists_ok'
[2025-08-22 18:57:24,332: INFO: main: >>>>> stage Data Ingestion Stage started >>>>>]
[2025-08-22 18:57:24,350: INFO: common: Yaml file: config\config.yaml is loaded successfully]
[2025-08-22 18:57:24,398: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-22 18:57:24,412: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-22 18:57:24,471: INFO: common: Directory created at artifacts]
[2025-08-22 18:57:24,507: INFO: common: Directory created at artifacts/data_ingestion]
[2025-08-22 18:57:26,189: INFO: data_ingestion: File artifacts/data_ingestion/data.zip downloaded with the following info: Date: Fri, 22 Aug 2025 13:57:26 GMT
Content-Type: text/html; charset=utf-8
Vary: X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, X-Requested-With,Accept-Encoding, Accept, X-Requested-With
x-repository-download: git clone https://github.com/krishnaik06/datasets.git
x-raw-download: https://raw.githubusercontent.com/krishnaik06/datasets/main/winequality-data.zip
ETag: W/"bcf64efea65b22e585040a6027ed0ae4"
Cache-Control: max-age=0, private, must-revalidate
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
Referrer-Policy: no-referrer-when-downgrade
Content-Security-Policy: default-src 'none'; base-uri 'self'; child-src github.githubassets.com github.com/assets-cdn/worker/ github.com/assets/ gist.github.com/assets-cdn/worker/; connect-src 'self' uploads.github.com www.githubstatus.com collector.github.com raw.githubusercontent.com api.github.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com *.rel.tunnels.api.visualstudio.com wss://*.rel.tunnels.api.visualstudio.com objects-origin.githubusercontent.com copilot-proxy.githubusercontent.com proxy.individual.githubcopilot.com proxy.business.githubcopilot.com proxy.enterprise.githubcopilot.com *.actions.githubusercontent.com wss://*.actions.githubusercontent.com productionresultssa0.blob.core.windows.net/ productionresultssa1.blob.core.windows.net/ productionresultssa2.blob.core.windows.net/ productionresultssa3.blob.core.windows.net/ productionresultssa4.blob.core.windows.net/ productionresultssa5.blob.core.windows.net/ productionresultssa6.blob.core.windows.net/ productionresultssa7.blob.core.windows.net/ productionresultssa8.blob.core.windows.net/ productionresultssa9.blob.core.windows.net/ productionresultssa10.blob.core.windows.net/ productionresultssa11.blob.core.windows.net/ productionresultssa12.blob.core.windows.net/ productionresultssa13.blob.core.windows.net/ productionresultssa14.blob.core.windows.net/ productionresultssa15.blob.core.windows.net/ productionresultssa16.blob.core.windows.net/ productionresultssa17.blob.core.windows.net/ productionresultssa18.blob.core.windows.net/ productionresultssa19.blob.core.windows.net/ github-production-repository-image-32fea6.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com insights.github.com wss://alive.github.com wss://alive-staging.github.com api.githubcopilot.com api.individual.githubcopilot.com api.business.githubcopilot.com api.enterprise.githubcopilot.com; font-src github.githubassets.com; form-action 'self' github.com gist.github.com copilot-workspace.githubnext.com objects-origin.githubusercontent.com; frame-ancestors 'none'; frame-src viewscreen.githubusercontent.com notebooks.githubusercontent.com; img-src 'self' data: blob: github.githubassets.com media.githubusercontent.com camo.githubusercontent.com identicons.github.com avatars.githubusercontent.com private-avatars.githubusercontent.com github-cloud.s3.amazonaws.com objects.githubusercontent.com release-assets.githubusercontent.com secured-user-images.githubusercontent.com/ user-images.githubusercontent.com/ private-user-images.githubusercontent.com opengraph.githubassets.com copilotprodattachments.blob.core.windows.net/github-production-copilot-attachments/ github-production-user-asset-6210df.s3.amazonaws.com customer-stories-feed.github.com spotlights-feed.github.com objects-origin.githubusercontent.com *.githubusercontent.com; manifest-src 'self'; media-src github.com user-images.githubusercontent.com/ secured-user-images.githubusercontent.com/ private-user-images.githubusercontent.com github-production-user-asset-6210df.s3.amazonaws.com gist.github.com; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com; upgrade-insecure-requests; worker-src github.githubassets.com github.com/assets-cdn/worker/ github.com/assets/ gist.github.com/assets-cdn/worker/
Server: github.com
Accept-Ranges: bytes
Set-Cookie: _gh_sess=iPCuXkNqhagPgJXWaV0m5tJneS4KRJdcFEYjT5%2FRQWqGD%2B6Vxv0egaeXoD7eAlHRUuhznc3NiOIOGH%2FK%2BEHMC4NEtnvavzmbSRtyLTt%2FtBf45jIul%2FHjv0DdNekA1TngPvIyhzO431puJ1qBrqN%2B8g2DZM0SUfA4NxC7mrP8VOfGED3CJCaKKTKh5NcBhWyfdsAIyodPuZbUQz%2Bd1FvorwxZnssURCrQvwh8VxJ1Bq9wKZh9Owp9KR78UgLp%2FX3gQps5APqcz0sIWU%2FJfQeLCQ%3D%3D--fkpBtf6pptNgygQW--SxFWBBBFnwntwRqE7YwZgQ%3D%3D; Path=/; HttpOnly; Secure; SameSite=Lax
Set-Cookie: _octo=GH1.1.801944078.1755871045; Path=/; Domain=github.com; Expires=Sat, 22 Aug 2026 13:57:25 GMT; Secure; SameSite=Lax
Set-Cookie: logged_in=no; Path=/; Domain=github.com; Expires=Sat, 22 Aug 2026 13:57:25 GMT; HttpOnly; Secure; SameSite=Lax
X-GitHub-Request-Id: 42EE:10A146:5130D0:5AB093:68A87745
connection: close
Transfer-Encoding: chunked

]
[2025-08-22 18:57:26,464: ERROR: main: File is not a zip file]
Traceback (most recent call last):
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\main.py", line 11, in <module>
    obj.initiate_data_ingestion()
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\pipeline\DataIngestionPipeline.py", line 17, in initiate_data_ingestion
    data_ingestion.extract_zip_file()
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\components\data_ingestion.py", line 23, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\Lib\zipfile.py", line 1302, in __init__
    self._RealGetContents()
  File "D:\anaconda\Lib\zipfile.py", line 1369, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2025-08-22 19:00:56,598: INFO: main: >>>>> stage Data Ingestion Stage started >>>>>]
[2025-08-22 19:00:56,608: INFO: common: Yaml file: config\config.yaml is loaded successfully]
[2025-08-22 19:00:56,621: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-22 19:00:56,623: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-22 19:00:56,626: INFO: common: Directory created at artifacts]
[2025-08-22 19:00:56,628: INFO: common: Directory created at artifacts/data_ingestion]
[2025-08-22 19:00:58,809: INFO: data_ingestion: File artifacts/data_ingestion/data.zip downloaded with the following info: Date: Fri, 22 Aug 2025 14:00:58 GMT
Content-Type: text/html; charset=utf-8
Vary: X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, X-Requested-With,Accept-Encoding, Accept, X-Requested-With
x-repository-download: git clone https://github.com/krishnaik06/datasets.git
x-raw-download: https://raw.githubusercontent.com/krishnaik06/datasets/main/winequality-data.zip
ETag: W/"0cc843f32dea9ba3f05e3f5b3dee26b8"
Cache-Control: max-age=0, private, must-revalidate
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
Referrer-Policy: no-referrer-when-downgrade
Content-Security-Policy: default-src 'none'; base-uri 'self'; child-src github.githubassets.com github.com/assets-cdn/worker/ github.com/assets/ gist.github.com/assets-cdn/worker/; connect-src 'self' uploads.github.com www.githubstatus.com collector.github.com raw.githubusercontent.com api.github.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com *.rel.tunnels.api.visualstudio.com wss://*.rel.tunnels.api.visualstudio.com objects-origin.githubusercontent.com copilot-proxy.githubusercontent.com proxy.individual.githubcopilot.com proxy.business.githubcopilot.com proxy.enterprise.githubcopilot.com *.actions.githubusercontent.com wss://*.actions.githubusercontent.com productionresultssa0.blob.core.windows.net/ productionresultssa1.blob.core.windows.net/ productionresultssa2.blob.core.windows.net/ productionresultssa3.blob.core.windows.net/ productionresultssa4.blob.core.windows.net/ productionresultssa5.blob.core.windows.net/ productionresultssa6.blob.core.windows.net/ productionresultssa7.blob.core.windows.net/ productionresultssa8.blob.core.windows.net/ productionresultssa9.blob.core.windows.net/ productionresultssa10.blob.core.windows.net/ productionresultssa11.blob.core.windows.net/ productionresultssa12.blob.core.windows.net/ productionresultssa13.blob.core.windows.net/ productionresultssa14.blob.core.windows.net/ productionresultssa15.blob.core.windows.net/ productionresultssa16.blob.core.windows.net/ productionresultssa17.blob.core.windows.net/ productionresultssa18.blob.core.windows.net/ productionresultssa19.blob.core.windows.net/ github-production-repository-image-32fea6.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com insights.github.com wss://alive.github.com wss://alive-staging.github.com api.githubcopilot.com api.individual.githubcopilot.com api.business.githubcopilot.com api.enterprise.githubcopilot.com; font-src github.githubassets.com; form-action 'self' github.com gist.github.com copilot-workspace.githubnext.com objects-origin.githubusercontent.com; frame-ancestors 'none'; frame-src viewscreen.githubusercontent.com notebooks.githubusercontent.com; img-src 'self' data: blob: github.githubassets.com media.githubusercontent.com camo.githubusercontent.com identicons.github.com avatars.githubusercontent.com private-avatars.githubusercontent.com github-cloud.s3.amazonaws.com objects.githubusercontent.com release-assets.githubusercontent.com secured-user-images.githubusercontent.com/ user-images.githubusercontent.com/ private-user-images.githubusercontent.com opengraph.githubassets.com copilotprodattachments.blob.core.windows.net/github-production-copilot-attachments/ github-production-user-asset-6210df.s3.amazonaws.com customer-stories-feed.github.com spotlights-feed.github.com objects-origin.githubusercontent.com *.githubusercontent.com; manifest-src 'self'; media-src github.com user-images.githubusercontent.com/ secured-user-images.githubusercontent.com/ private-user-images.githubusercontent.com github-production-user-asset-6210df.s3.amazonaws.com gist.github.com; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com; upgrade-insecure-requests; worker-src github.githubassets.com github.com/assets-cdn/worker/ github.com/assets/ gist.github.com/assets-cdn/worker/
Server: github.com
Accept-Ranges: bytes
Set-Cookie: _gh_sess=5zcfPGRLwbDlXq7wuriveV47jYb34sq%2BVimwkDDTBS6Q2Bzhw1W0lsdr4UqPRnb808uENSkO24tbZfHTeiI%2Bs82K7HJTcjec9a0H9GmtoLyMhaeG9vyo57Up%2Fishx1ClzagxyFsgaZxY8F5O0E2FF5X3Dn3w8Oge67IgeRLXaoSMZki7Iq1rRnu72%2B7VuByl6MGGoxJwRXEG9%2FuEozF4D9zJJ%2F8ZV1XmKQjh0egSOJxMapwdo7znHfvNzpI4XTCGiFsMbCWbwcLQvrNPvKvSVw%3D%3D--Li8QO5yywh%2FRC1Vm--OS49sw%2FlXUe%2FemFaEMO7Xw%3D%3D; Path=/; HttpOnly; Secure; SameSite=Lax
Set-Cookie: _octo=GH1.1.127869588.1755871258; Path=/; Domain=github.com; Expires=Sat, 22 Aug 2026 14:00:58 GMT; Secure; SameSite=Lax
Set-Cookie: logged_in=no; Path=/; Domain=github.com; Expires=Sat, 22 Aug 2026 14:00:58 GMT; HttpOnly; Secure; SameSite=Lax
X-GitHub-Request-Id: 4486:112C5C:514B22:5AE8E5:68A8781A
connection: close
Transfer-Encoding: chunked

]
[2025-08-22 19:00:59,018: ERROR: main: File is not a zip file]
Traceback (most recent call last):
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\main.py", line 11, in <module>
    obj.initiate_data_ingestion()
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\pipeline\DataIngestionPipeline.py", line 17, in initiate_data_ingestion
    data_ingestion.extract_zip_file()
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\components\data_ingestion.py", line 23, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\Lib\zipfile.py", line 1302, in __init__
    self._RealGetContents()
  File "D:\anaconda\Lib\zipfile.py", line 1369, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2025-08-23 07:55:15,599: INFO: main: >>>>> stage Data Ingestion Stage started >>>>>]
[2025-08-23 07:55:15,628: INFO: common: Yaml file: config\config.yaml is loaded successfully]
[2025-08-23 07:55:15,658: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 07:55:15,660: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 07:55:15,662: INFO: common: Directory created at artifacts]
[2025-08-23 07:55:15,663: INFO: common: Directory created at artifacts/data_ingestion]
[2025-08-23 07:55:16,821: INFO: data_ingestion: File artifacts/data_ingestion/data.zip downloaded with the following info: Date: Sat, 23 Aug 2025 02:55:17 GMT
Content-Type: text/html; charset=utf-8
Vary: X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, X-Requested-With,Accept-Encoding, Accept, X-Requested-With
x-repository-download: git clone https://github.com/krishnaik06/datasets.git
x-raw-download: https://raw.githubusercontent.com/krishnaik06/datasets/main/winequality-data.zip
ETag: W/"d02f71ae949a04b1ca27149ab7e0ea53"
Cache-Control: max-age=0, private, must-revalidate
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
Referrer-Policy: no-referrer-when-downgrade
Content-Security-Policy: default-src 'none'; base-uri 'self'; child-src github.githubassets.com github.com/assets-cdn/worker/ github.com/assets/ gist.github.com/assets-cdn/worker/; connect-src 'self' uploads.github.com www.githubstatus.com collector.github.com raw.githubusercontent.com api.github.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com *.rel.tunnels.api.visualstudio.com wss://*.rel.tunnels.api.visualstudio.com objects-origin.githubusercontent.com copilot-proxy.githubusercontent.com proxy.individual.githubcopilot.com proxy.business.githubcopilot.com proxy.enterprise.githubcopilot.com *.actions.githubusercontent.com wss://*.actions.githubusercontent.com productionresultssa0.blob.core.windows.net/ productionresultssa1.blob.core.windows.net/ productionresultssa2.blob.core.windows.net/ productionresultssa3.blob.core.windows.net/ productionresultssa4.blob.core.windows.net/ productionresultssa5.blob.core.windows.net/ productionresultssa6.blob.core.windows.net/ productionresultssa7.blob.core.windows.net/ productionresultssa8.blob.core.windows.net/ productionresultssa9.blob.core.windows.net/ productionresultssa10.blob.core.windows.net/ productionresultssa11.blob.core.windows.net/ productionresultssa12.blob.core.windows.net/ productionresultssa13.blob.core.windows.net/ productionresultssa14.blob.core.windows.net/ productionresultssa15.blob.core.windows.net/ productionresultssa16.blob.core.windows.net/ productionresultssa17.blob.core.windows.net/ productionresultssa18.blob.core.windows.net/ productionresultssa19.blob.core.windows.net/ github-production-repository-image-32fea6.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com insights.github.com wss://alive.github.com wss://alive-staging.github.com api.githubcopilot.com api.individual.githubcopilot.com api.business.githubcopilot.com api.enterprise.githubcopilot.com; font-src github.githubassets.com; form-action 'self' github.com gist.github.com copilot-workspace.githubnext.com objects-origin.githubusercontent.com; frame-ancestors 'none'; frame-src viewscreen.githubusercontent.com notebooks.githubusercontent.com; img-src 'self' data: blob: github.githubassets.com media.githubusercontent.com camo.githubusercontent.com identicons.github.com avatars.githubusercontent.com private-avatars.githubusercontent.com github-cloud.s3.amazonaws.com objects.githubusercontent.com release-assets.githubusercontent.com secured-user-images.githubusercontent.com/ user-images.githubusercontent.com/ private-user-images.githubusercontent.com opengraph.githubassets.com copilotprodattachments.blob.core.windows.net/github-production-copilot-attachments/ github-production-user-asset-6210df.s3.amazonaws.com customer-stories-feed.github.com spotlights-feed.github.com objects-origin.githubusercontent.com *.githubusercontent.com; manifest-src 'self'; media-src github.com user-images.githubusercontent.com/ secured-user-images.githubusercontent.com/ private-user-images.githubusercontent.com github-production-user-asset-6210df.s3.amazonaws.com gist.github.com; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com; upgrade-insecure-requests; worker-src github.githubassets.com github.com/assets-cdn/worker/ github.com/assets/ gist.github.com/assets-cdn/worker/
Server: github.com
Accept-Ranges: bytes
Set-Cookie: _gh_sess=FB1Imh8S5QrYHoQXzzf4mKVPD1qblrlvrv%2F0GOLclkupg1sGNJWqEwzE5ra6jlFG1fDFU0i9QwRc9S9DEPuqcDboMZulKLBerGBM3YepWLHVZmAZKVo76uLvtzdGaTXdUbfKuou8IofMCaP80DuJO7t0PkYVsQUYnJgBbducdyekEN9ASdo5SvHfyBRLDrPe9O34cYA9hl9PGrCmqQ6XF%2FZzcajRGxmeJ59V94T4p7lt%2FC5HbPYBZIYDEFj7%2BXtrGyScKXswFY%2FWg40SuLRmrQ%3D%3D--tEwolbtQTLv%2B21dO--s98pLulD1lX8hwAKwTRZtg%3D%3D; Path=/; HttpOnly; Secure; SameSite=Lax
Set-Cookie: _octo=GH1.1.1328515705.1755917716; Path=/; Domain=github.com; Expires=Sun, 23 Aug 2026 02:55:16 GMT; Secure; SameSite=Lax
Set-Cookie: logged_in=no; Path=/; Domain=github.com; Expires=Sun, 23 Aug 2026 02:55:16 GMT; HttpOnly; Secure; SameSite=Lax
X-GitHub-Request-Id: 99F3:E0EB5:FBA64:1891FD:68A92D94
connection: close
Transfer-Encoding: chunked

]
[2025-08-23 07:55:17,187: ERROR: main: File is not a zip file]
Traceback (most recent call last):
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\main.py", line 11, in <module>
    obj.initiate_data_ingestion()
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\pipeline\DataIngestionPipeline.py", line 17, in initiate_data_ingestion
    data_ingestion.extract_zip_file()
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\components\data_ingestion.py", line 24, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\Lib\zipfile.py", line 1302, in __init__
    self._RealGetContents()
  File "D:\anaconda\Lib\zipfile.py", line 1369, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2025-08-23 08:05:36,948: INFO: main: >>>>> stage Data Ingestion Stage started >>>>>]
[2025-08-23 08:05:36,954: INFO: common: Yaml file: config\config.yaml is loaded successfully]
[2025-08-23 08:05:36,961: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 08:05:36,962: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 08:05:36,963: INFO: common: Directory created at artifacts]
[2025-08-23 08:05:36,964: INFO: common: Directory created at artifacts/data_ingestion]
[2025-08-23 08:05:36,965: INFO: data_ingestion: File already exists]
[2025-08-23 08:05:36,967: ERROR: main: name 'config' is not defined]
Traceback (most recent call last):
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\main.py", line 11, in <module>
    obj.initiate_data_ingestion()
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\pipeline\DataIngestionPipeline.py", line 17, in initiate_data_ingestion
    data_ingestion.extract_zip_file()
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\components\data_ingestion.py", line 24, in extract_zip_file
    print(type(config.local_data_file))
               ^^^^^^
NameError: name 'config' is not defined
[2025-08-23 08:05:55,909: INFO: main: >>>>> stage Data Ingestion Stage started >>>>>]
[2025-08-23 08:05:55,925: INFO: common: Yaml file: config\config.yaml is loaded successfully]
[2025-08-23 08:05:55,928: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 08:05:55,930: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 08:05:55,931: INFO: common: Directory created at artifacts]
[2025-08-23 08:05:55,931: INFO: common: Directory created at artifacts/data_ingestion]
[2025-08-23 08:05:55,933: INFO: data_ingestion: File already exists]
[2025-08-23 08:05:55,981: ERROR: main: File is not a zip file]
Traceback (most recent call last):
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\main.py", line 11, in <module>
    obj.initiate_data_ingestion()
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\pipeline\DataIngestionPipeline.py", line 17, in initiate_data_ingestion
    data_ingestion.extract_zip_file()
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\components\data_ingestion.py", line 26, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\Lib\zipfile.py", line 1302, in __init__
    self._RealGetContents()
  File "D:\anaconda\Lib\zipfile.py", line 1369, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2025-08-23 08:24:04,926: INFO: main: >>>>> stage Data Ingestion Stage started >>>>>]
[2025-08-23 08:24:04,929: INFO: common: Yaml file: config\config.yaml is loaded successfully]
[2025-08-23 08:24:04,932: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 08:24:04,934: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 08:24:04,935: INFO: common: Directory created at artifacts]
[2025-08-23 08:24:04,936: INFO: common: Directory created at artifacts/data_ingestion]
[2025-08-23 08:24:05,782: INFO: data_ingestion: File artifacts/data_ingestion/data.zip downloaded with the following info: Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 607E:316EC2:23381C:2A863E:68A93456
Accept-Ranges: bytes
Date: Sat, 23 Aug 2025 03:24:06 GMT
Via: 1.1 varnish
X-Served-By: cache-mrs1050095-MRS
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1755919446.385429,VS0,VE204
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: b399ebf6baaf7b9304bc30499c4b3d57bf4d36e6
Expires: Sat, 23 Aug 2025 03:29:06 GMT
Source-Age: 0

]
[2025-08-23 08:24:05,825: INFO: main: >>>>> stage Data Ingestion Stage completed >>>>>]
[2025-08-23 08:24:05,830: INFO: main: Alhumdullillah sb okay h boss!]
[2025-08-23 09:52:28,284: INFO: main: >>>>> stage Data Ingestion Stage started >>>>>]
[2025-08-23 09:52:28,290: INFO: common: Yaml file: config\config.yaml is loaded successfully]
[2025-08-23 09:52:28,295: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 09:52:28,297: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 09:52:28,298: INFO: common: Directory created at artifacts]
[2025-08-23 09:52:28,299: INFO: common: Directory created at artifacts/data_ingestion]
[2025-08-23 09:52:28,300: INFO: data_ingestion: File already exists]
[2025-08-23 09:52:28,363: INFO: main: >>>>> stage Data Ingestion Stage completed >>>>>]
[2025-08-23 09:52:28,364: INFO: main: Alhumdullillah sb okay h boss!]
[2025-08-23 09:52:28,364: INFO: main: >>>>> stage Data Validation Stage started >>>>>]
[2025-08-23 09:52:28,369: INFO: common: Yaml file: config\config.yaml is loaded successfully]
[2025-08-23 09:52:28,371: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 09:52:28,373: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 09:52:28,373: INFO: common: Directory created at artifacts]
[2025-08-23 09:52:28,374: ERROR: main: "'ConfigBox' object has no attribute 'columns'"]
Traceback (most recent call last):
  File "box\\box.py", line 594, in box.box.Box.__getitem__
KeyError: 'COLUMNS'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\box.py", line 633, in box.box.Box.__getattr__
  File "box\\box.py", line 621, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'COLUMNS'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 635, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'COLUMNS'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\config_box.py", line 29, in box.config_box.ConfigBox.__getattr__
  File "box\\box.py", line 649, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'COLUMNS'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 594, in box.box.Box.__getitem__
KeyError: 'columns'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\box.py", line 633, in box.box.Box.__getattr__
  File "box\\box.py", line 621, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'columns'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 635, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'columns'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\main.py", line 25, in <module>
    obj.initiate_data_validation()
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\pipeline\DataValidationPipeline.py", line 13, in initiate_data_validation
    data_validation_config = config.get_data_validation_config()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\config\configuration.py", line 34, in get_data_validation_config
    schema = self.schema.COLUMNS
             ^^^^^^^^^^^^^^^^^^^
  File "box\\config_box.py", line 31, in box.config_box.ConfigBox.__getattr__
  File "box\\box.py", line 649, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'columns'"
[2025-08-23 09:56:08,399: INFO: main: >>>>> stage Data Ingestion Stage started >>>>>]
[2025-08-23 09:56:08,404: INFO: common: Yaml file: config\config.yaml is loaded successfully]
[2025-08-23 09:56:08,406: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 09:56:08,411: INFO: common: Yaml file: schema.yaml is loaded successfully]
[2025-08-23 09:56:08,413: INFO: common: Directory created at artifacts]
[2025-08-23 09:56:08,415: INFO: common: Directory created at artifacts/data_ingestion]
[2025-08-23 09:56:08,415: INFO: data_ingestion: File already exists]
[2025-08-23 09:56:08,423: INFO: main: >>>>> stage Data Ingestion Stage completed >>>>>]
[2025-08-23 09:56:08,424: INFO: main: Alhumdullillah sb okay h boss!]
[2025-08-23 09:56:08,425: INFO: main: >>>>> stage Data Validation Stage started >>>>>]
[2025-08-23 09:56:08,437: INFO: common: Yaml file: config\config.yaml is loaded successfully]
[2025-08-23 09:56:08,439: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 09:56:08,453: INFO: common: Yaml file: schema.yaml is loaded successfully]
[2025-08-23 09:56:08,468: INFO: common: Directory created at artifacts]
[2025-08-23 09:56:08,469: ERROR: main: create_directories() missing 1 required positional argument: 'verbose']
Traceback (most recent call last):
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\main.py", line 25, in <module>
    obj.initiate_data_validation()
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\pipeline\DataValidationPipeline.py", line 13, in initiate_data_validation
    data_validation_config = config.get_data_validation_config()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\config\configuration.py", line 36, in get_data_validation_config
    create_directories([config.root_dir])
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\.venv\Lib\site-packages\ensure\main.py", line 835, in __call__
    return self.f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: create_directories() missing 1 required positional argument: 'verbose'
[2025-08-23 09:56:55,289: INFO: main: >>>>> stage Data Ingestion Stage started >>>>>]
[2025-08-23 09:56:55,297: INFO: common: Yaml file: config\config.yaml is loaded successfully]
[2025-08-23 09:56:55,299: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 09:56:55,307: INFO: common: Yaml file: schema.yaml is loaded successfully]
[2025-08-23 09:56:55,308: INFO: common: Directory created at artifacts]
[2025-08-23 09:56:55,310: INFO: common: Directory created at artifacts/data_ingestion]
[2025-08-23 09:56:55,310: INFO: data_ingestion: File already exists]
[2025-08-23 09:56:55,318: INFO: main: >>>>> stage Data Ingestion Stage completed >>>>>]
[2025-08-23 09:56:55,325: INFO: main: Alhumdullillah sb okay h boss!]
[2025-08-23 09:56:55,325: INFO: main: >>>>> stage Data Validation Stage started >>>>>]
[2025-08-23 09:56:55,337: INFO: common: Yaml file: config\config.yaml is loaded successfully]
[2025-08-23 09:56:55,339: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 09:56:55,363: INFO: common: Yaml file: schema.yaml is loaded successfully]
[2025-08-23 09:56:55,387: INFO: common: Directory created at artifacts]
[2025-08-23 09:56:55,389: INFO: common: Directory created at artifacts/data_validation]
[2025-08-23 09:56:55,390: ERROR: main: "'ConfigBox' object has no attribute 'unzip_data_dir'"]
Traceback (most recent call last):
  File "box\\box.py", line 594, in box.box.Box.__getitem__
KeyError: 'unzip_data_dir'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\box.py", line 633, in box.box.Box.__getattr__
  File "box\\box.py", line 621, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'unzip_data_dir'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 635, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'unzip_data_dir'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\config_box.py", line 29, in box.config_box.ConfigBox.__getattr__
  File "box\\box.py", line 649, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'unzip_data_dir'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 594, in box.box.Box.__getitem__
KeyError: 'unzip_data_dir'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\box.py", line 633, in box.box.Box.__getattr__
  File "box\\box.py", line 621, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'unzip_data_dir'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 635, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'unzip_data_dir'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\main.py", line 25, in <module>
    obj.initiate_data_validation()
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\pipeline\DataValidationPipeline.py", line 13, in initiate_data_validation
    data_validation_config = config.get_data_validation_config()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\config\configuration.py", line 41, in get_data_validation_config
    unzip_data_dir=config.unzip_data_dir,
                   ^^^^^^^^^^^^^^^^^^^^^
  File "box\\config_box.py", line 31, in box.config_box.ConfigBox.__getattr__
  File "box\\box.py", line 649, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'unzip_data_dir'"
[2025-08-23 09:57:46,818: INFO: main: >>>>> stage Data Ingestion Stage started >>>>>]
[2025-08-23 09:57:46,822: INFO: common: Yaml file: config\config.yaml is loaded successfully]
[2025-08-23 09:57:46,824: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 09:57:46,831: INFO: common: Yaml file: schema.yaml is loaded successfully]
[2025-08-23 09:57:46,833: INFO: common: Directory created at artifacts]
[2025-08-23 09:57:46,835: INFO: common: Directory created at artifacts/data_ingestion]
[2025-08-23 09:57:46,836: INFO: data_ingestion: File already exists]
[2025-08-23 09:57:46,851: INFO: main: >>>>> stage Data Ingestion Stage completed >>>>>]
[2025-08-23 09:57:46,854: INFO: main: Alhumdullillah sb okay h boss!]
[2025-08-23 09:57:46,856: INFO: main: >>>>> stage Data Validation Stage started >>>>>]
[2025-08-23 09:57:46,870: INFO: common: Yaml file: config\config.yaml is loaded successfully]
[2025-08-23 09:57:46,873: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 09:57:46,886: INFO: common: Yaml file: schema.yaml is loaded successfully]
[2025-08-23 09:57:46,891: INFO: common: Directory created at artifacts]
[2025-08-23 09:57:46,892: INFO: common: Directory created at artifacts/data_validation]
[2025-08-23 09:57:46,893: ERROR: main: 'DataValidation' object has no attribute 'congif']
Traceback (most recent call last):
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\main.py", line 25, in <module>
    obj.initiate_data_validation()
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\pipeline\DataValidationPipeline.py", line 15, in initiate_data_validation
    data_validation.validate_all_columns()
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\components\data_validation.py", line 31, in validate_all_columns
    raise e
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\components\data_validation.py", line 14, in validate_all_columns
    data = pd.read_csv(self.congif.unzip_data_dir)
                       ^^^^^^^^^^^
AttributeError: 'DataValidation' object has no attribute 'congif'
[2025-08-23 09:58:32,910: INFO: main: >>>>> stage Data Ingestion Stage started >>>>>]
[2025-08-23 09:58:32,913: INFO: common: Yaml file: config\config.yaml is loaded successfully]
[2025-08-23 09:58:32,915: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 09:58:32,919: INFO: common: Yaml file: schema.yaml is loaded successfully]
[2025-08-23 09:58:32,920: INFO: common: Directory created at artifacts]
[2025-08-23 09:58:32,922: INFO: common: Directory created at artifacts/data_ingestion]
[2025-08-23 09:58:32,923: INFO: data_ingestion: File already exists]
[2025-08-23 09:58:32,930: INFO: main: >>>>> stage Data Ingestion Stage completed >>>>>]
[2025-08-23 09:58:32,931: INFO: main: Alhumdullillah sb okay h boss!]
[2025-08-23 09:58:32,931: INFO: main: >>>>> stage Data Validation Stage started >>>>>]
[2025-08-23 09:58:32,934: INFO: common: Yaml file: config\config.yaml is loaded successfully]
[2025-08-23 09:58:32,936: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 09:58:32,943: INFO: common: Yaml file: schema.yaml is loaded successfully]
[2025-08-23 09:58:32,949: INFO: common: Directory created at artifacts]
[2025-08-23 09:58:32,950: INFO: common: Directory created at artifacts/data_validation]
[2025-08-23 09:58:33,078: INFO: main: >>>>> stage Data Validation Stage completed >>>>>]
[2025-08-23 12:02:36,432: INFO: main: >>>>> stage Data Ingestion Stage started >>>>>]
[2025-08-23 12:02:36,439: INFO: common: Yaml file: config\config.yaml is loaded successfully]
[2025-08-23 12:02:36,446: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 12:02:36,451: INFO: common: Yaml file: schema.yaml is loaded successfully]
[2025-08-23 12:02:36,452: INFO: common: Directory created at artifacts]
[2025-08-23 12:02:36,454: INFO: common: Directory created at artifacts/data_ingestion]
[2025-08-23 12:02:36,454: INFO: data_ingestion: File already exists]
[2025-08-23 12:02:36,470: INFO: main: >>>>> stage Data Ingestion Stage completed >>>>>]
[2025-08-23 12:02:36,483: INFO: main: Alhumdullillah sb okay h boss!]
[2025-08-23 12:02:36,493: INFO: main: >>>>> stage Data Validation Stage started >>>>>]
[2025-08-23 12:02:36,530: INFO: common: Yaml file: config\config.yaml is loaded successfully]
[2025-08-23 12:02:36,537: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 12:02:36,547: INFO: common: Yaml file: schema.yaml is loaded successfully]
[2025-08-23 12:02:36,549: INFO: common: Directory created at artifacts]
[2025-08-23 12:02:36,557: INFO: common: Directory created at artifacts/data_validation]
[2025-08-23 12:02:36,661: INFO: main: >>>>> stage Data Validation Stage completed >>>>>]
[2025-08-23 12:02:36,662: INFO: main: >>>>> stage Data Transformation Stage started >>>>>]
[2025-08-23 12:02:36,662: ERROR: main: name 'Path' is not defined]
Traceback (most recent call last):
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\main.py", line 37, in <module>
    obj.initiate_data_transformation()
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\pipeline\DataTransformationPipeline.py", line 22, in initiate_data_transformation
    raise e
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\pipeline\DataTransformationPipeline.py", line 11, in initiate_data_transformation
    with open(Path('artifacts/data_validation/STATUS_FILE.txt'),'r') as f:
              ^^^^
NameError: name 'Path' is not defined
[2025-08-23 12:03:00,734: INFO: main: >>>>> stage Data Ingestion Stage started >>>>>]
[2025-08-23 12:03:00,738: INFO: common: Yaml file: config\config.yaml is loaded successfully]
[2025-08-23 12:03:00,739: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 12:03:00,744: INFO: common: Yaml file: schema.yaml is loaded successfully]
[2025-08-23 12:03:00,745: INFO: common: Directory created at artifacts]
[2025-08-23 12:03:00,746: INFO: common: Directory created at artifacts/data_ingestion]
[2025-08-23 12:03:00,747: INFO: data_ingestion: File already exists]
[2025-08-23 12:03:00,753: INFO: main: >>>>> stage Data Ingestion Stage completed >>>>>]
[2025-08-23 12:03:00,753: INFO: main: Alhumdullillah sb okay h boss!]
[2025-08-23 12:03:00,754: INFO: main: >>>>> stage Data Validation Stage started >>>>>]
[2025-08-23 12:03:00,757: INFO: common: Yaml file: config\config.yaml is loaded successfully]
[2025-08-23 12:03:00,759: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 12:03:00,765: INFO: common: Yaml file: schema.yaml is loaded successfully]
[2025-08-23 12:03:00,766: INFO: common: Directory created at artifacts]
[2025-08-23 12:03:00,768: INFO: common: Directory created at artifacts/data_validation]
[2025-08-23 12:03:00,837: INFO: main: >>>>> stage Data Validation Stage completed >>>>>]
[2025-08-23 12:03:00,838: INFO: main: >>>>> stage Data Transformation Stage started >>>>>]
[2025-08-23 12:03:00,840: ERROR: main: [Errno 2] No such file or directory: 'artifacts\\data_validation\\STATUS_FILE.txt']
Traceback (most recent call last):
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\main.py", line 37, in <module>
    obj.initiate_data_transformation()
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\pipeline\DataTransformationPipeline.py", line 23, in initiate_data_transformation
    raise e
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\pipeline\DataTransformationPipeline.py", line 12, in initiate_data_transformation
    with open(Path('artifacts/data_validation/STATUS_FILE.txt'),'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\data_validation\\STATUS_FILE.txt'
[2025-08-23 12:04:08,208: INFO: main: >>>>> stage Data Ingestion Stage started >>>>>]
[2025-08-23 12:04:08,213: INFO: common: Yaml file: config\config.yaml is loaded successfully]
[2025-08-23 12:04:08,215: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 12:04:08,222: INFO: common: Yaml file: schema.yaml is loaded successfully]
[2025-08-23 12:04:08,224: INFO: common: Directory created at artifacts]
[2025-08-23 12:04:08,226: INFO: common: Directory created at artifacts/data_ingestion]
[2025-08-23 12:04:08,226: INFO: data_ingestion: File already exists]
[2025-08-23 12:04:08,240: INFO: main: >>>>> stage Data Ingestion Stage completed >>>>>]
[2025-08-23 12:04:08,244: INFO: main: Alhumdullillah sb okay h boss!]
[2025-08-23 12:04:08,245: INFO: main: >>>>> stage Data Validation Stage started >>>>>]
[2025-08-23 12:04:08,253: INFO: common: Yaml file: config\config.yaml is loaded successfully]
[2025-08-23 12:04:08,255: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 12:04:08,262: INFO: common: Yaml file: schema.yaml is loaded successfully]
[2025-08-23 12:04:08,265: INFO: common: Directory created at artifacts]
[2025-08-23 12:04:08,266: INFO: common: Directory created at artifacts/data_validation]
[2025-08-23 12:04:08,349: INFO: main: >>>>> stage Data Validation Stage completed >>>>>]
[2025-08-23 12:04:08,349: INFO: main: >>>>> stage Data Transformation Stage started >>>>>]
[2025-08-23 12:04:08,358: INFO: common: Yaml file: config\config.yaml is loaded successfully]
[2025-08-23 12:04:08,361: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 12:04:08,366: INFO: common: Yaml file: schema.yaml is loaded successfully]
[2025-08-23 12:04:08,367: INFO: common: Directory created at artifacts]
[2025-08-23 12:04:08,369: ERROR: main: 'ConfigurationManager' object has no attribute 'get_data_transformation']
Traceback (most recent call last):
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\main.py", line 37, in <module>
    obj.initiate_data_transformation()
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\pipeline\DataTransformationPipeline.py", line 23, in initiate_data_transformation
    raise e
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\pipeline\DataTransformationPipeline.py", line 17, in initiate_data_transformation
    data_transformation_config = config.get_data_transformation()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigurationManager' object has no attribute 'get_data_transformation'
[2025-08-23 12:05:31,530: INFO: main: >>>>> stage Data Ingestion Stage started >>>>>]
[2025-08-23 12:05:31,534: INFO: common: Yaml file: config\config.yaml is loaded successfully]
[2025-08-23 12:05:31,536: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 12:05:31,540: INFO: common: Yaml file: schema.yaml is loaded successfully]
[2025-08-23 12:05:31,541: INFO: common: Directory created at artifacts]
[2025-08-23 12:05:31,543: INFO: common: Directory created at artifacts/data_ingestion]
[2025-08-23 12:05:31,543: INFO: data_ingestion: File already exists]
[2025-08-23 12:05:31,548: INFO: main: >>>>> stage Data Ingestion Stage completed >>>>>]
[2025-08-23 12:05:31,550: INFO: main: Alhumdullillah sb okay h boss!]
[2025-08-23 12:05:31,551: INFO: main: >>>>> stage Data Validation Stage started >>>>>]
[2025-08-23 12:05:31,554: INFO: common: Yaml file: config\config.yaml is loaded successfully]
[2025-08-23 12:05:31,556: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 12:05:31,560: INFO: common: Yaml file: schema.yaml is loaded successfully]
[2025-08-23 12:05:31,562: INFO: common: Directory created at artifacts]
[2025-08-23 12:05:31,563: INFO: common: Directory created at artifacts/data_validation]
[2025-08-23 12:05:31,637: INFO: main: >>>>> stage Data Validation Stage completed >>>>>]
[2025-08-23 12:05:31,638: INFO: main: >>>>> stage Data Transformation Stage started >>>>>]
[2025-08-23 12:05:31,644: INFO: common: Yaml file: config\config.yaml is loaded successfully]
[2025-08-23 12:05:31,646: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 12:05:31,649: INFO: common: Yaml file: schema.yaml is loaded successfully]
[2025-08-23 12:05:31,650: INFO: common: Directory created at artifacts]
[2025-08-23 12:05:31,651: INFO: common: Directory created at artifacts/data_transformation]
[2025-08-23 12:05:31,750: INFO: data_transformation: Spliting completed]
[2025-08-23 12:05:31,751: INFO: data_transformation: Train shape: (1199, 12)]
[2025-08-23 12:05:31,751: ERROR: main: name 'loger' is not defined]
Traceback (most recent call last):
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\main.py", line 37, in <module>
    obj.initiate_data_transformation()
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\pipeline\DataTransformationPipeline.py", line 23, in initiate_data_transformation
    raise e
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\pipeline\DataTransformationPipeline.py", line 19, in initiate_data_transformation
    data_transformation.train_test_spliting()
  File "C:\Users\ABDULLAH RIZWAN\OneDrive\Desktop\Data Sciences\MLOPS\DataScienceProject\src\DataScienceProject\components\data_transformation.py", line 22, in train_test_spliting
    loger.info(f'Test  shape: {test.shape}')
    ^^^^^
NameError: name 'loger' is not defined
[2025-08-23 12:06:04,401: INFO: main: >>>>> stage Data Ingestion Stage started >>>>>]
[2025-08-23 12:06:04,407: INFO: common: Yaml file: config\config.yaml is loaded successfully]
[2025-08-23 12:06:04,409: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 12:06:04,415: INFO: common: Yaml file: schema.yaml is loaded successfully]
[2025-08-23 12:06:04,417: INFO: common: Directory created at artifacts]
[2025-08-23 12:06:04,418: INFO: common: Directory created at artifacts/data_ingestion]
[2025-08-23 12:06:04,418: INFO: data_ingestion: File already exists]
[2025-08-23 12:06:04,428: INFO: main: >>>>> stage Data Ingestion Stage completed >>>>>]
[2025-08-23 12:06:04,429: INFO: main: Alhumdullillah sb okay h boss!]
[2025-08-23 12:06:04,434: INFO: main: >>>>> stage Data Validation Stage started >>>>>]
[2025-08-23 12:06:04,507: INFO: common: Yaml file: config\config.yaml is loaded successfully]
[2025-08-23 12:06:04,535: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 12:06:04,553: INFO: common: Yaml file: schema.yaml is loaded successfully]
[2025-08-23 12:06:04,607: INFO: common: Directory created at artifacts]
[2025-08-23 12:06:04,619: INFO: common: Directory created at artifacts/data_validation]
[2025-08-23 12:06:04,722: INFO: main: >>>>> stage Data Validation Stage completed >>>>>]
[2025-08-23 12:06:04,723: INFO: main: >>>>> stage Data Transformation Stage started >>>>>]
[2025-08-23 12:06:04,730: INFO: common: Yaml file: config\config.yaml is loaded successfully]
[2025-08-23 12:06:04,732: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 12:06:04,736: INFO: common: Yaml file: schema.yaml is loaded successfully]
[2025-08-23 12:06:04,738: INFO: common: Directory created at artifacts]
[2025-08-23 12:06:04,739: INFO: common: Directory created at artifacts/data_transformation]
[2025-08-23 12:06:04,828: INFO: data_transformation: Spliting completed]
[2025-08-23 12:06:04,830: INFO: data_transformation: Train shape: (1199, 12)]
[2025-08-23 12:06:04,832: INFO: data_transformation: Test  shape: (400, 12)]
[2025-08-23 12:06:04,832: INFO: main: >>>>> stage Data Transformation Stage completed >>>>>]
[2025-08-23 12:06:53,230: INFO: main: >>>>> stage Data Ingestion Stage started >>>>>]
[2025-08-23 12:06:53,234: INFO: common: Yaml file: config\config.yaml is loaded successfully]
[2025-08-23 12:06:53,235: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 12:06:53,238: INFO: common: Yaml file: schema.yaml is loaded successfully]
[2025-08-23 12:06:53,239: INFO: common: Directory created at artifacts]
[2025-08-23 12:06:53,239: INFO: common: Directory created at artifacts/data_ingestion]
[2025-08-23 12:06:53,239: INFO: data_ingestion: File already exists]
[2025-08-23 12:06:53,243: INFO: main: >>>>> stage Data Ingestion Stage completed >>>>>]
[2025-08-23 12:06:53,244: INFO: main: Alhumdullillah sb okay h boss!]
[2025-08-23 12:06:53,244: INFO: main: >>>>> stage Data Validation Stage started >>>>>]
[2025-08-23 12:06:53,246: INFO: common: Yaml file: config\config.yaml is loaded successfully]
[2025-08-23 12:06:53,248: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 12:06:53,252: INFO: common: Yaml file: schema.yaml is loaded successfully]
[2025-08-23 12:06:53,253: INFO: common: Directory created at artifacts]
[2025-08-23 12:06:53,254: INFO: common: Directory created at artifacts/data_validation]
[2025-08-23 12:06:53,321: INFO: main: >>>>> stage Data Validation Stage completed >>>>>]
[2025-08-23 12:06:53,321: INFO: main: >>>>> stage Data Transformation Stage started >>>>>]
[2025-08-23 12:06:53,325: INFO: common: Yaml file: config\config.yaml is loaded successfully]
[2025-08-23 12:06:53,326: INFO: common: Yaml file: params.yaml is loaded successfully]
[2025-08-23 12:06:53,329: INFO: common: Yaml file: schema.yaml is loaded successfully]
[2025-08-23 12:06:53,330: INFO: common: Directory created at artifacts]
[2025-08-23 12:06:53,330: INFO: common: Directory created at artifacts/data_transformation]
[2025-08-23 12:06:53,370: INFO: data_transformation: Spliting completed]
[2025-08-23 12:06:53,371: INFO: data_transformation: Train shape: (1199, 12)]
[2025-08-23 12:06:53,372: INFO: data_transformation: Test  shape: (400, 12)]
[2025-08-23 12:06:53,372: INFO: main: >>>>> stage Data Transformation Stage completed >>>>>]
